def game_changer():
    move()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    turn_left()

game_changer()
game_changer()
game_changer()
game_changer()
game_changer()
game_changer()